name: .NET Core
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore "./DemoCICD-QOTD"
    - name: Build code
      run: dotnet build "./DemoCICD-QOTD" --configuration Release --no-restore
    - name: Test code 
      run: dotnet test "./DemoCICD-QOTD" --no-restore --verbosity normal
    - name: Publish application
      run: dotnet publish "./myApp" -c Release -o myApp
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: "./DemoCICD-QOTD"
